CREATE TABLE IF NOT EXISTS production_tickets
(
    ticket_id           int          NOT NULL AUTO_INCREMENT,
    production_note_1   varchar(255) DEFAULT NULL,
    production_note_2   varchar(255) DEFAULT NULL,
    production_note_3   varchar(255) DEFAULT NULL,
    production_note_4   varchar(255) DEFAULT NULL,
    production_note_5   varchar(255) DEFAULT NULL,
    production_note_6   varchar(255) DEFAULT NULL,
    aluminium_tim_type  varchar(255) DEFAULT NULL,
    aluminium_tube_type varchar(255) DEFAULT NULL,
    bristle_diameter    float        DEFAULT NULL,
    bristle_type        varchar(255) DEFAULT NULL,
    customer_id         varchar(255) DEFAULT NULL,
    done_packaging_at   datetime(6)  DEFAULT NULL,
    done_preparing_at   datetime(6)  DEFAULT NULL,
    done_trimming_at    datetime(6)  DEFAULT NULL,
    done_twining_at     datetime(6)  DEFAULT NULL,
    due_date            date         DEFAULT NULL,
    inner_tube_type     varchar(255) DEFAULT NULL,
    issued_at           datetime(6)  NOT NULL,
    model               varchar(255) DEFAULT NULL,
    model_note          varchar(255) DEFAULT NULL,
    order_id            int          NOT NULL,
    packaged_by         varchar(255) DEFAULT NULL,
    prepared_by         varchar(255) DEFAULT NULL,
    product_entry_id    varchar(255) NOT NULL,
    product_name        varchar(255) DEFAULT NULL,
    quantity            int          DEFAULT NULL,
    trimmed_by          varchar(255) DEFAULT NULL,
    twined_by           varchar(255) DEFAULT NULL,
    PRIMARY KEY (ticket_id)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8;